name: CI

on:
  push:
  pull_request:

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 2.7
      versions: '["debug"]'

  test:
    needs: ruby-versions
    name: ${{ matrix.os }}/${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-22.04
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: actions/cache@v4
      with:
        path: ~/.cache/red-datasets
        key: ${{ runner.os }}-${{ hashFiles('charty.gemspec') }}
        restore-keys: ${{ runner.os }}-

    - run: sudo apt install build-essential libsqlite3-dev

    - run: npm install playwright@latest
    - run: ./node_modules/.bin/playwright install

    - run: bundle install --jobs 4 --retry 3 --without "nmatrix python"

    - run: bundle exec rake

    - run: rake build

    - run: gem install --user pkg/*.gem
