name: CI with matplotlib and pandas

on:
  push:
  pull_request:

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: "3.1"
      versions: '["debug"]'

  test:
    needs: ruby-versions
    name: ${{ matrix.os }}/${{ matrix.ruby }}/${{ matrix.python }}-${{ matrix.python_architecture }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-22.04
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        python:
        - 3.x
        python_architecture:
        - x64

    steps:
    - uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_architecture }}

    - uses: actions/cache@v4
      with:
        path: ~/.cache/red-datasets
        key: ${{ runner.os }}-${{ hashFiles('charty.gemspec') }}
        restore-keys: ${{ runner.os }}-

    - run: sudo apt install build-essential libsqlite3-dev

    - run: npm install playwright@latest
    - run: ./node_modules/.bin/playwright install

    - run: pip install --user matplotlib pandas

    - run: bundle install --jobs 4 --retry 3 --without "nmatrix numo"

    - run: python -V

    - run: bundle exec rake
      env:
        PYTHON: python
